> # 0x05. Python - Excepciones
---
| **Filename** | **Description** |
|---|---|
|[0. Safe list printing](./0-safe_print_list.py)| function that prints `x` elements of a list.  |
|[1. Safe printing of an integers list](./1-safe_print_integer.py)|  function that prints an integer with `"{:d}".format()`.  |
|[2. Print and count integers](./2-safe_print_list_integers.py)| function that prints the first `x` elements of a list and only integers.  |
|[3. Integers division with debug ](./3-safe_print_division.py)|  function that divides 2 integers and prints the result.  |
|[4. Divide a list](./4-list_division.py)|  function that divides element by element 2 lists.  |
|[5. Raise exception](./5-raise_exception.py)| function that raises a type exception.  |
|[6. Raise a message](./6-raise_exception_msg.py)| function that raises a name exception with a message.  |
|   |   |
---
> ## contact ðŸ’¬

### | [twitter](https://twitter.com/RICARDO1470) | [linkedin](https://www.linkedin.com/in/ricardo-alfonso-camayo/) | [mail](1466@holbertonschool.com) | [github](https://github.com/ricardo1470/README/blob/master/README.md) |
---
